### ISSUE TITLE
python3 issues

### ISSUE THREAD

**Issue by szaboodoora** [neuropower/neurodesign#10] opened 2019-09-30 11:49 UTC
xrange & sys.exc_clear() are deprecated since python 3.x
I forked this version https://github.com/PeerHerholz/neurodesign
and modified it here https://github.com/szaboodoora/neurodesign/commit/77f6081236ed41a1b5cb82ec820891259e3a6bde 
to make it work with python3
Thanks for creating this tool!

**Comment by amazinger13** [comment] 2020-09-26 06:21
Great work. But when I tried to use 
         git install git+https://github.com/PeerHerholz/neurodesign.git
to install this package, an error occured: 
 Running command git clone -q https://github.com/PeerHerholz/neurodesign.git 'C:\Users\Yang Guochun\AppData\Local\Temp\pip-req-build-k4p8wj7x'
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Yang Guochun\\AppData\\Local\\Temp\\pip-req-build-k4p8wj7x\\setup.py'"'"'; __file__='"'"'C:\\Users\\Yang Guochun\\AppData\\Local\\Temp\\pip-req-build-k4p8wj7x\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Yang Guochun\AppData\Local\Temp\pip-pip-egg-info-1inip9pi'
         cwd: C:\Users\Yang Guochun\AppData\Local\Temp\pip-req-build-k4p8wj7x\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\ProgramData\Anaconda3\lib\tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Yang Guochun\\AppData\\Local\\Temp\\pip-req-build-k4p8wj7x\\setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
It is the same case with the https://github.com/neuropower/neurodesign.git
Could this problem be fixed? Thanks

**Comment by amazinger13** [comment] 2020-09-26 10:14
> Great work. But when I tried to use
> git install git+https://github.com/PeerHerholz/neurodesign.git
> to install this package, an error occured:
> Running command git clone -q https://github.com/PeerHerholz/neurodesign.git 'C:\Users\Yang Guochun\AppData\Local\Temp\pip-req-build-k4p8wj7x'
> ERROR: Command errored out with exit status 1:
> command: 'C:\ProgramData\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Yang Guochun\AppData\Local\Temp\pip-req-build-k4p8wj7x\setup.py'"'"'; **file**='"'"'C:\Users\Yang Guochun\AppData\Local\Temp\pip-req-build-k4p8wj7x\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Yang Guochun\AppData\Local\Temp\pip-pip-egg-info-1inip9pi'
> cwd: C:\Users\Yang Guochun\AppData\Local\Temp\pip-req-build-k4p8wj7x
> Complete output (5 lines):
> Traceback (most recent call last):
> File "", line 1, in 
> File "C:\ProgramData\Anaconda3\lib\tokenize.py", line 392, in open
> buffer = _builtin_open(filename, 'rb')
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Yang Guochun\AppData\Local\Temp\pip-req-build-k4p8wj7x\setup.py'
> ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> It is the same case with the https://github.com/neuropower/neurodesign.git
> Could this problem be fixed? Thanks

I have just solved the problem.
This error occured because the github repository does not contain the setup.py file in its initial directory. It was inside the "source" directory instead. I just moved all the contents from source directory into the initial directory. Further I also corrected all the problems caused by function incompatibility in python 3. The corrected repository could be found at https://github.com/amazinger13/neurodesign.git.

**Comment by Remi-Gau** [comment] 2024-02-16 16:25
should be fixed

**Closed as completed by Remi-Gau** 2024-02-16 16:25 UTC
